### ISSUE TITLE
iOS: Adding PointAnnotation with custom child causes map performance to drop

### ISSUE THREAD

**Issue by michalpierzchlewicz** [rnmapbox/maps#1309]
---------  

**Describe the bug**  
On iOS device, when I add a PointAnnotation component with custom children (works well with default marker - i.e. no children or when using Callout component), when I start moving the map or zooming in and out, the framerate drops down significantly

**To Reproduce**  
Create a MapView with a single PointAnnotation component, with children (e.g. View component). Then start zooming in and out and moving the map around. You will see a significant drop in framerate.

Example:
```js
import React from 'react';
import {
  MapView,
  PointAnnotation,
  Camera,
} from '@react-native-mapbox-gl/maps';

class BugReportExample extends React.Component {
  render() {
    return (
      <MapView style={{flex: 1}}>
        <Camera centerCoordinate={[-122.452652, 37.762963]} zoomLevel={14} />
        <PointAnnotation
          id='idPointAnnotation'
          coordinate={[-122.452652, 37.762963]}
        >
          <View
            style={{
              width: 40,
              height: 40,
              backgroundColor: 'red',
            }}
          />
        </PointAnnotation>
      </MapView>
    );
  }
}
```

**Expected behavior**  
The framerate should not drop.

**Actual behavior**  
Framerate drops when moving or zooming the map.

**Screenshots** 
If you look at the performance monitor, you will see a significant drop in framerate.
![ezgif-6-896f18386612](https://user-images.githubusercontent.com/17205976/114215888-7430c800-9966-11eb-92b8-931a458aa8e5.gif)

**Versions (please complete the following information):**  
 - Platform: iOS
 - Platform OS: iOS 14.4
 - Device: iPhone X
 - Emulator/ Simulator: no
 - Dev OS: macOS 10.15.1
 - react-native-mapbox-gl Version 8.2.0-beta1
 - React Native Version 0.63.3

**Additional context**  
Works well if remove the View component from inside the PointAnnotation component.

**Comment by ferdicus** [comment]
hey, thanks for opening a ticket - which `mapbox-sdk` version are you using?

**Comment by badredaha** [comment]
🙋‍♂️🙋‍♂️🙋‍♂️ same thing Here :/

**Comment by ferdicus** [comment]
again, underlying native SDK?  
Did you try with another version?

**Comment by badredaha** [comment]
5.9.0

**Comment by ferdicus** [comment]
Can you try with `6.3.0` and report back please.   
Also, just to be super sure - this is on physical devices, yes?

**Comment by DimaDP** [comment]
Same thing with markerView on ios 14.6 and no problem on 13. *

**Comment by appstart-lt** [comment]
Ran into the exact same issue.

Resolved by:
1. Upgrading RN library to `8.2.1`.
2. Adding `$ReactNativeMapboxGLIOSVersion = '~> 6.3.0'` to the Podfile.

**Comment by ferdicus** [comment]
hey @michalpierzchlewicz, 
does this still occur?  
I assumed this was pretty imported to you and the other people from the company upvoting your initial description? 

Did you manage to fix this by upgrading? 

Without any feedback we can't look at this/ will close due to inactivity. 


Cheers 🍻

**Comment by sdacunha** [comment]
Hi,

Facing the same issue unfortunately. Using the Expo managed workflow + the expo plugin with 8.3.0.
Unfortunately, on iOS, adding a child to the PointAnnotation component causes rendering issues whenever I move the camera (fitBounds, setCamera, etc).

For now for the static pins I can use a ShapeSource + SymbolLayer, but I feel like this will become a blocker when I need dynamic content to be rendered.

FWIW, the same code does not experience frame drops on Android.

**Comment by Pietro-Putelli** [comment]
Hi, using the latest version of the library I'm still get the same problem!
