### ISSUE TITLE
Wrong position of MarkerView

### ISSUE THREAD

**Issue by Crysp** [rnmapbox/maps#2115]
## Environment

- Mapbox (GL) implementation: v10
- Mapbox (GL) version: 10.7.0
- @rnmapbox/maps Version #main
- Platform: iOS
- React Native Version 0.69.4
- Platform OS: iOS 15
- Device: iPhone X
- Emulator/ Simulator: simulator and physical device
- Dev OS: macOS Monterey 12

## Standalone component to reproduce

```js
import React from 'react';
import { View } from 'react-native';
import {
  MapView,
  ShapeSource,
  Camera,
  CircleLayer,
  MarkerView,
} from '@rnmapbox/maps';

const coordinate = [30.319378097536216, 59.879647222152855];

const BugReport = () => (
  <MapView style={{ flex: 1 }}>
    <Camera
      defaultSettings={{
        centerCoordinate: coordinate,
        zoomLevel: 16,
      }}
    />
    <ShapeSource
      id='point'
      shape={{
        type: 'Point',
        coordinates: coordinate,
      }}
    >
      <CircleLayer
        id='circle'
        style={{ circleRadius: 10, circleColor: 'black' }}
      />
    </ShapeSource>
    <MarkerView id='marker' coordinate={coordinate}>
      <View
        style={{
          width: 60,
          height: 60,
          borderRadius: 30,
          backgroundColor: 'rgba(255,0,0,0.5)',
        }}
      />
    </MarkerView>
  </MapView>
);
```

## Observed behavior and steps to reproduce

<img src="https://user-images.githubusercontent.com/13776478/184087087-a8287916-0e6c-4d74-b25a-ddb33a70a7f5.png" width="360">

## Expected behavior

<img src="https://user-images.githubusercontent.com/13776478/184087205-f7eeaf74-69fc-4679-b70a-d25faa64be24.png" width="360">

## Notes / preliminary analysis

`PointAnnotation` displays perfectly

I think it's because initialized with wrong bounds (should be 60 instead of 375)

<img width="499" alt="Screenshot 2022-08-11 at 10 56 51" src="https://user-images.githubusercontent.com/13776478/184089171-a72c9fb3-abe8-4bbc-8a07-f1d754eb71fe.png">

**Comment by Crysp** [comment]
@mlandauer If marker visibility depends on component state it renders incorrectly. I used component in incorrect way or it is a bug?

```jsx
import React, { useState } from 'react';
import { View } from 'react-native';
import {
  MapView,
  ShapeSource,
  Camera,
  CircleLayer,
  MarkerView,
} from '@rnmapbox/maps';

const coordinate = [30.319378097536216, 59.879647222152855];

const BugReport = () => {
  const [visible, setVisible] = useState(false);
  return (
    <MapView style={{ flex: 1 }}>
      <Camera
        defaultSettings={{
          centerCoordinate: coordinate,
          zoomLevel: 16,
        }}
      />
      <ShapeSource
        id='point'
        shape={{
          type: 'Point',
          coordinates: coordinate,
        }}
        onPress={() => setVisible(true)}
      >
        <CircleLayer
          id='circle'
          style={{ circleRadius: 10, circleColor: 'black' }}
        />
      </ShapeSource>
      {visible && (
        <MarkerView id='marker' coordinate={coordinate}>
          <View
            style={{
              width: 60,
              height: 60,
              borderRadius: 30,
              backgroundColor: 'rgba(255,0,0,0.5)',
            }}
          />
        </MarkerView>
      )}
    </MapView>
  );
};
```

<img src="https://user-images.githubusercontent.com/13776478/184839760-cee515d1-82b3-43f3-b37f-c2c128e85b3d.png" width="360">

Also it fires the warning (even if render marker without condition)
```Mapbox [warn] MarkerView: No subview to render {"level": "warn", "message": "MarkerView: No subview to render"}```

**Comment by rusakovic** [comment]
@Crysp Confirm the same warning

![image](https://user-images.githubusercontent.com/17801144/187085458-2b0ea4eb-31ff-4739-b301-4d638d2f546e.png)

@Crysp Could you, please, confirm that `MarkerView` is rendering in your app with latest mapbox version?


Plus, docs I think outdated https://github.com/rnmapbox/maps/blob/main/docs/MarkerView.md
`id`, `coordinate` and `children` are only required.

![image](https://user-images.githubusercontent.com/17801144/187085505-ab01324e-33c0-4e15-a2a2-9da532481a4d.png)

**Comment by Crysp** [comment]
@rusakovic marker renders as i described at previous post (at the top left corner)

- Mapbox (GL) version: 10.7.0
- @rnmapbox/maps Version #v10.0.0-beta.32

**Comment by michaek** [comment]
@rusakovic @mfazekas I can also confirm that this issue is not resolved, testing with `@rnmapbox/maps@rnmapbox/maps#main` commit https://github.com/rnmapbox/maps/commit/7c39991facf6e0745f53f39afaf3792539525f1a 

I am observing the log message "MarkerView: No subview to render" and the marker view rendered in a fixed position, not relative to map coordinates.

**Comment by michaek** [comment]
Since there is an example that reproduces the issue against the current HEAD, it seems that this issue should be reopened.

**Comment by michaek** [comment]
(It appears that the "MarkerView: No subview to render" message may be spurious for this issue - at least the one from `_updateFrameOrAnchor` - because it is invoked before `addToMap` so we would expect there to be no subview at that point.)

Having looked at this example in the XCode debugger, I am seeing a similar behavior of the `bounds` object in `RCTMGLMarkerView.addToMap`, though mine reliably has zero dimensions unless it is present in the first React render. I'm inclined to think this is not an issue, though. The bounds as calculated by React Native are correct following `reactSetFrame` and `_updateFrameOrAnchor`, and it looks like they are being passed correctly to a view update. 

However, after the initial render it seems the component is not doing what's needed to update the marker position. Unfortunately, it's not clear to me what is setting the marker position - I'd imagine that's coming from the value of `coordinate`, but I haven't followed exactly how that is translated to map position: **it seems to me that whenever `_updateCoordinate` updates the view with geometry, it's actually set in the options to `nil`**. Maybe this is the actual underlying issue?

For a case when there are a known number of markers, we could work around this by rendering the marker view on map mount and never removing it, just styling it invisible, but that isn't ideal and it certainly doesn't cover the case of dynamic markers based on arbitrary data. 😄 

Thanks!

**Comment by michaek** [comment]
I should also note that there are messages in the XCode logs like "[Mapbox] [Warning]: Cannot calculate position for annotation with id: 1 as the width or height is invalid" when this rendering error occurs. I don't yet see where the invalid width/height are coming from, or even what method this message comes from, but it seems likely to help uncover the cause.

**Comment by michaek** [comment]
For my use case I was able to refactor to use a SymbolLayer (though I would have preferred using the MarkerView approach), but I definitely don't want my absence to seem like confirmation that this issue is resolved.

**Comment by michaek** [comment]
I don't think I'll be able to test anytime soon, but there's a good possibility that #2203 has resolved this issue. Maybe someone who's reproduced this issue prior to that changeset could verify?

**Comment by cazzer** [comment]
I was experiencing this issue and it is resolved for me on `10.0.0-beta.43`!

**Comment by m90khan** [comment]
I installed the latest version.    "@rnmapbox/maps": "^10.0.0-beta.44",
Sadly, the issue still persists.

**Comment by traviswimer** [comment]
@m90khan 10.0.0-beta.44 seems to be working for me.

Are you sure the old version isn't still being used? I've made that mistake too many times.

In other words:

- Uninstall app from device
- Clean build folder
- Ensure `$RNMapboxMapsVersion` isn't set to an old version in `Podfile`
- Run `pod install`
- Run `react-native start -- --reset-cache`
- Probably other things...

The react-native CLI really needs a command to reset everything like this. I always seem to forget something.
