### ISSUE TITLE
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNMBXMapViewModule' could not be found.

### ISSUE THREAD

**Issue by erwanlpfr** [rnmapbox/maps#3193]
## Environment
- Dev OS: OSX

## Steps to reproduce

Hello!

With :
- react native 0.72.7
- rnmapbox 10.1.0-beta.21 with mapbox v10
- new arch : _false_

I get this error after launching the bundler and displaying the map

```bash
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNMBXMapViewModule' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes
```

This happens only with `beta 21` with clear cache.
It builds and starts with new arch activated, but my app is not ready yet. I wonder Mapbox is still compatible to old arch? 

Thank you for your work!

> I'm actually creating the repo to make you reproducing this! I edit this post soon

```sh   
react-native init sample --version 0.72.7
cd sample
npm i @rnmapbox/maps@10.1.0-beta.21
react-native run-android
```

In App.tsx
```tsx
import {MapView} from '@rnmapbox/maps';
import React from 'react';
import {SafeAreaView, StatusBar, useColorScheme} from 'react-native';
import {Colors} from 'react-native/Libraries/NewAppScreen';

function App() {
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  return (
    <SafeAreaView style={backgroundStyle}>
      <StatusBar
        barStyle={isDarkMode ? 'light-content' : 'dark-content'}
        backgroundColor={backgroundStyle.backgroundColor}
      />
      <MapView style={{height: 300}} />
    </SafeAreaView>
  );
}

export default App;

```

Additional logs : 
```txt

 LOG  Running "sample" with {"rootTag":11}
 ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNMBXMapViewModule' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes 
    at App (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.sample&modulesOnly=false&runModule=true:122495:54)
    at RCTView
    at View (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.sample&modulesOnly=false&runModule=true:59470:43)
    at RCTView
    at View (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.sample&modulesOnly=false&runModule=true:59470:43)
    at AppContainer (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.sample&modulesOnly=false&runModule=true:59314:36)
    at sample(RootComponent) (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.sample&modulesOnly=false&runModule=true:108030:28)
 ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNMBXMapViewModule' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes 
    at App (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.sample&modulesOnly=false&runModule=true:122495:54)
    at RCTView
    at View (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.sample&modulesOnly=false&runModule=true:59470:43)
    at RCTView
    at View (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.sample&modulesOnly=false&runModule=true:59470:43)
    at AppContainer (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.sample&modulesOnly=false&runModule=true:59314:36)
    at sample(RootComponent) (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.sample&modulesOnly=false&runModule=true:108030:28)
 ERROR  TypeError: Cannot read property 'MapView' of undefined

This error is located at:
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in sample(RootComponent), js engine: hermes
 ERROR  TypeError: Cannot read property 'MapView' of undefined

This error is located at:
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in sample(RootComponent), js engine: hermes
```

**Comment by mfazekas** [comment]
@erwanlpfr are you sure you can repro it on a project created with `react-native init`? We do support old-arch for sure

**Comment by erwanlpfr** [comment]
> @erwanlpfr are you sure you can repro it on a project created with `react-native init`? We do support old-arch for sure

I'm trying to make the repro the most closed to my env. I'll ping you when it is done ! Thanks!

**Comment by erwanlpfr** [comment]
@mfazekas As it, I get the issue, you can follow the repro!

**Comment by ysainson** [comment]
Experiencing this issue on Android with `10.1.0-beta.21`. No problems on iOS.

**Comment by mfazekas** [comment]
Can you try with rc? We might not be able with build with beta.5

```
 RNMapboxMapsVersion: "11.0.0-beta.5",
 ```

**Comment by mfazekas** [comment]
> Reproducible with the react native init.

Is it? You're using expo aren't you?!

Have you verified your RNMapboxMapsDownloadToken has the right permissions?

**Comment by erwanlpfr** [comment]
No, no Expo, pure React Native 0.72.7 !

I just retried and here, you can find the repro.

```bash
npx react-native init sample --version 0.72.7
cd sample
npm i @rnmapbox/maps@10.1.0-beta.22
npx react-native run-android
```

```bash
 LOG  Running "sample" with {"rootTag":11}
 ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNMBXMapViewModule' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes
    at App (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.sample&modulesOnly=false&runModule=true:122489:54)
    at RCTView
    at View (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.sample&modulesOnly=false&runModule=true:59470:43)
    at RCTView
    at View (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.sample&modulesOnly=false&runModule=true:59470:43)
    at AppContainer (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.sample&modulesOnly=false&runModule=true:59314:36)
    at sample(RootComponent) (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.sample&modulesOnly=false&runModule=true:108030:28)
 ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNMBXMapViewModule' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes
    at App (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.sample&modulesOnly=false&runModule=true:122489:54)
    at RCTView
    at View (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.sample&modulesOnly=false&runModule=true:59470:43)
    at RCTView
    at View (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.sample&modulesOnly=false&runModule=true:59470:43)
    at AppContainer (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.sample&modulesOnly=false&runModule=true:59314:36)
    at sample(RootComponent) (http://10.0.2.2:8081/index.bundle//&platform=android&dev=true&minify=false&app=com.sample&modulesOnly=false&runModule=true:108030:28)
 ERROR  TypeError: Cannot read property 'MapView' of undefined

This error is located at:
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in sample(RootComponent), js engine: hermes
 ERROR  TypeError: Cannot read property 'MapView' of undefined

This error is located at:
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in sample(RootComponent), js engine: hermes
```

It looks like it came from this commit ?
https://github.com/rnmapbox/maps/compare/v10.1.0-beta.20...v10.1.0-beta.21#diff-e41dc52beb74b889c738e750118cdb5bb8b3ab2ee412a77b3a248b2b394e1d01R25

Thank you for your work!

**Comment by mfazekas** [comment]
@erwanlpfr thank much, yes so in beta.21 and 22 I've upgraded the codegen to 0.73 and it seems that 0.73 generates code for oldgen that's no longer compatible with 0.72. Ugh.... so even if our example is 0.73 we still need to use 0.72 codegen to generate code that's compatible with older versions.

**Comment by mfazekas** [comment]
@erwanlpfr thanks much for the report.  👍 

I've release a new beta 23 which should fix the issue

**Comment by erwanlpfr** [comment]
Thank you for taking time on this! 👍🏻

**Comment by ysainson** [comment]
I can confirm that the issue has been resolved in version `10.1.0-beta.23`. Thanks @mfazekas!

**Comment by AshwinPetari** [comment]
@mfazekas This issue still occurs with RN: 0.73.1 and rnmapbox/maps@10.1.3. Any solution for this?

`Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNMBXMapViewModule' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: false. TurboModule interop: false. Modules loaded: {"NativeModules":["PlatformConstants","LogBox","Timing","AppState","SourceCode","BlobModule","WebSocketModule","SettingsManager","DevSettings","RedBox","Networking","Appearance","DevLoadingView","UIManager","DeviceInfo","ImageLoader","LinkingManager","RNCSafeAreaContext","I18nManager","NativeAnimatedModule"],"TurboModules":[],"NotFound":["NativePerformanceCxx","NativePerformanceObserverCxx","BugReporting","HeadlessJsTaskSupport","SoundManager","IntentAndroid","RNMBXMapViewModule"]}, js engine: hermes

ERROR  Error: Exception in HostObject::get for prop 'RNMBXLocationModule': java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/android/core/location/LocationEngineCallback;, js engine: hermes`

**Comment by AdzeB** [comment]
Can confirm I am getting the same issue for this but I am on `v10.1.3-rc.0`

**Comment by atif089** [comment]
I'm facing the same issue in the following environment

* "expo": "^49.0.10",
* "@rnmapbox/maps": v10.1.3-rc.0,
* Android API 31

**Comment by daveyholler** [comment]
I'm getting the same issue with the following:
* "expo": "~49.0.15"
* "react-native": "0.72.6"
* "@rnmapbox/maps": "^10.1.3"
* iOS 17.2

**Comment by mfazekas** [comment]
Can you reproduce with a new project from  ```npx create-expo-app``` ?! Can you post the steps to reproduce and a link to a repo (pls do not include access tokens).

**Comment by NitayMG** [comment]
Got this error too:
 ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNMBXMapViewModule' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes
 
 using react native with Expo 
 expo ver: 48.0.21
 react native ver: 0.71.14
 everything works just fine till I update  from @rnmapbox/maps  10.0.15 to @rnmapbox/maps   10.1.5

**Comment by NitayMG** [comment]
> Can you reproduce with a new project from `npx create-expo-app` ?! Can you post the steps to reproduce and a link to a repo (pls do not include access tokens).

steps to reproduce:
create account at mapbox...create token with download:read 
npx create-expo-app MYAPP
npm install @rnmapbox/maps
add to app.json:
"plugins": [
      [
        "@rnmapbox/maps",
        {
          "RNMapboxMapsImpl": "mapbox",
          "RNMapboxMapsDownloadToken": "sk.",
          "RNMapboxMapsVersion": "11.0.0",
          "RNMapboxMapsUseV11": true
        }
      ]
    ]
  }
  
  make simple component with mapbox:
  
  import React from 'react';
import { StyleSheet, View } from 'react-native';
import Mapbox from '@rnmapbox/maps';

Mapbox.setAccessToken('<YOUR_ACCESSTOKEN>');

const App = () => {
  return (
    <View style={styles.page}>
      <View style={styles.container}>
        <Mapbox.MapView style={styles.map} />
      </View>
    </View>
  );
}

export default App;

const styles = StyleSheet.create({
  page: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    height: 300,
    width: 300,
  },
  map: {
    flex: 1
  }
});

When you try to run it on emulator with:
npx expo start --dev-client
you will get this crash

**Comment by Omkar001-afk** [comment]
I am facing the following issue,
 Error: @rnmapbox/maps native code not available. Make sure you have linked the library and rebuild your app. See https://rnmapbox.github.io/docs/install?rebuild=expo#rebuild, js engine: hermes
![Image (1)](https://github.com/rnmapbox/maps/assets/83110014/bb50ee4a-ae0b-4d94-85b7-2ad71dd70933)
![Image](https://github.com/rnmapbox/maps/assets/83110014/f7d0a973-a4de-46e0-a723-584bf8853148)
![image](https://github.com/rnmapbox/maps/assets/83110014/2c101563-fdf0-4962-9900-83cf9d3ad82b)

**Comment by NitayMG** [comment]
STEPS To fix:
1.npm update
2. npm install -g eas-cli
3. npx expo install expo-dev-client
4.eas build --profile development --platform android
5. for run on andorid emulator: npx expo start --dev-client

**Comment by Omkar001-afk** [comment]
is there any other packages to install
![image](https://github.com/rnmapbox/maps/assets/83110014/041b8b58-0200-4bea-af3a-6f8718566ca8)

**Comment by NitayMG** [comment]
You need to update and after the update do a rebuild to your emulator:
- npm update
- after update
- eas build --profile development --platform android

**Comment by Omkar001-afk** [comment]
Thanks its working and is there any other steps for production.

**Comment by NitayMG** [comment]
For making an apk you use this command:
eas build -p android --profile preview

**Comment by brianestadimas** [comment]
This issue is not yet solved

**Comment by whitewaterdesign** [comment]
Same issue here...
```
"@rnmapbox/maps": "^10.1.18",
```
```
[
        '@rnmapbox/maps',
        {
          RNMapboxMapsDownloadToken: [SECRET_ACCESS_TOKEN_WITH_DOWNLOAD_PERMISSIONS],
          RNMapboxMapsVersion: '11.1.0',
        },
      ]
```

**Comment by tortortortortortor** [comment]
same issue here.
<img width="631" alt="image" src="https://github.com/rnmapbox/maps/assets/114900680/799055e7-e863-4953-b4bd-b179c8972e9f">
<img width="387" alt="image" src="https://github.com/rnmapbox/maps/assets/114900680/8bc8a37b-7379-43d5-b52f-9a67770792e6">
<img width="381" alt="image" src="https://github.com/rnmapbox/maps/assets/114900680/6e259eed-ac9a-4f69-9c64-8035f1fd5a79">
